ecommerce/accounts/urls.py
# coding=utf-8

"""accounts URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from accounts import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
]

ecommerce/catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'), # ?P<slug> - Nomeando qual parametro estamos trabalhando, 'slug'
    url(r'^produto/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

ecommerce/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='register')),
    # url(r'^register/$', views.register, name='register'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': 'index'}, name='logout'),
]

ecommerce/core/models.py
from django.db import models

# Create your models here.

ecommerce/core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):
    """ Classe para o formulário de contato. """

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea)

    # Usando o gerenciamento do template form direto na sua classe, não recomendado.
    # def __init__(self, *args, **kwargs):
    #      super(ContactForm, self).__init__(*args, **kwargs)
    #      self.fields['name'].widget.attrs['class'] = 'form-control'
    #      self.fields['email'].widget.attrs['class'] = 'form-control'
    #      self.fields['message'].widget.attrs['class'] = 'form-control'

    def send_mail(self):
        name = self.cleaned_data ['name']
        email = self.cleaned_data ['email']
        message = self.cleaned_data ['message']
        message = 'Nome: {0}\nE-mail: {1}\n{2}'.format(name, email, message)
        # Argumentos send_email(subject, message, from_email, list_to_email)
        send_mail('Contato Django E-commerce', message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])

ecommerce/core/views.py
# coding=utf-8

from core.forms import ContactForm
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import TemplateView, View, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class IndexView(TemplateView):
    template_name = 'index.html'

index = IndexView.as_view()


# class LoginView(TemplateView):
#     template_name = 'login.html'
#
# login = LoginView.as_view()



def contact(request):
    success = False
    # Entede-se aqui como sendo uma operação ternária em Python. Caso a avaliação
    # boolena do primeira termo serja False, não existente, ele envia um None.
    # Se estamo passando um None, o DJango entende que nosso formulario nao está
    # preenchido e sem validar, o que não mostra mensagem de erro. Seria como uma
    # nova instanciação do mesmo: form = ContactForm()
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True

    context = {
        'title': 'Fale Conosco',
        'form': form,
        'success': success,
    }
    return render(request, 'contact.html', context)

ecommerce/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title_page %}
        Django E-Commerce
        {% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
        <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>
        <link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen"/>
        <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" media="screen"/>
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'index' %}" class="navbar-brand">
                        Django E-Commerce
                    </a>
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse" id="navbar-main">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'index' %}">Início</a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">
                                Categorias <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="download">
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}" >{{ category }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'contact' %}">Contato</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            {% if user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Olá, {{ user.get_short_name }} <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="download">
                                {% if user.is_superuser %}
                                <li>
                                    <a href="{% url 'admin:index' %}">
                                        <i class="fa fa-user-secret" aria-hidden="true"></i> Dango Admin
                                    </a>
                                </li>
                                {% endif %}

                                <li>
                                    <a href="{% url 'register:index' %}">
                                        <i class="fa fa-id-card-o" aria-hidden="true"></i> Minha Conta
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}" >
                                        <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                                    </a>
                                </li>
                            </ul>
                            {% else %}
                            <li class="dropdown">
                                <a href="{% url 'login' %}" class="dropdown-toggle" data-toggle="dropdown">
                                    Login / Cadastre-se
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="download">
                                    <li>
                                        <a href="{% url 'login' %}">
                                            <i class="fa fa-sign-in" aria-hidden="true"></i> Logar
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'register:register' %}" >
                                            <i class="fa fa-user" aria-hidden="true"></i> Cadastrar
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container margin-top">

            {% block container %} {% endblock container %}

            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                            <li class="pull-right"><a href="#top">Voltar ao Topo <i class="fa fa-arrow-up"></i></a></li>
                            <li><a href="{% url 'index' %}">Início</a></li>
                            <li><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
                            <li><a href="{% url 'contact' %}">Contato</a></li>
                            <li><a href="">Termos e Privacidade</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{% static 'assets/bootstrap.min.js' %}"></script>
    </body>
    </html>

ecommerce/core/templates/contact.html
{% extends "base.html" %}

{% comment %} Carregando a lib que vai gerenciar nosso template {% endcomment %}
{% load widget_tweaks %}

{% block title_page %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="page-header">
        {% if success %}
            <h1>Obrigado!</h1>
            <br><br>
            <div class="alert alert-success">
                Mensagem enviada com sucesso.
            </div>
        {% else %}
            <h1><i class="fa fa-envelope fa-1x" aria-hidden="true"></i> Fale conosco</h1>
            <br />
            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                        <div class="form-group {% if field.errors %} has-error {%endif %}">
                            <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="{% if field.name == 'message' %} col-md-6 {% else %} col-md-3 {%endif %}">
                                {% render_field field class='form-control' %}
                                {% for error in field.errors %}
                                    <span class="help-block error">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        {% endif %}
    </div>
{% endblock %}

ecommerce/core/templates/index.html
{% extends "base.html" %}

{% block title_page %}E-Commerce - Home{% endblock %}

{% block container %}
    <div class="jumbotron page-header">
        <h1>{{ 'Django E-commerce' }}</h1>
        <p>Donec sollicitudin molestie malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non
            nulla sit amet nisl tempus convallis quis ac lectus. Vestibulum ac diam sit amet quam vehicula elementum sed
            sit amet dui. Sed porttitor lectus nibh. Pellentesque in ipsum id orci porta dapibus. Pellentesque in ipsum
            id orci porta dapibus. Proin eget tortor risus. Curabitur aliquet quam id dui posuere blandit. Donec rutrum
            congue leo eget malesuada.</p>
        <p>
            <small>Curabitur aliquet quam id dui posuere blandit. Curabitur arcu erat, accumsan id imperdiet et,
                porttitor at sem.
            </small>
        <p><a class="btn btn-primary">Saiba mais</a></p>
    </div>
{% endblock %}

ecommerce/core/templates/login.html
{% extends "base.html" %}

{% block title_page %} Login | {{ block.super }} {% endblock title_page %}

{% load widget_tweaks %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1><i class="fa fa-sign-in" aria-hidden="true"></i> Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                    <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                    <div class="col-md-9">
                        {% render_field form.username class="form-control" %}
                        {% for error in form.username.errors %}
                            <span class="help-block error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                    <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                    <div class="col-md-9">
                        {% render_field form.password class="form-control" %}
                        {% for error in form.password.errors %}
                            <span class="help-block error">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                {% for error in form.non_field_errors %}
                    <div class="col-md-9 col-md-offset-3 alert alert-danger">
                        {{ error|linebreaks }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock container %}

ecommerce/core/templates/pagination.html
{% if paginator.num_pages > 1 %}
    <nav aria-label="Page navigation example">
      <ul class="pagination pagination-sm">
          <li class="page-item {% if page_obj.number == 1 %}disabled{% endif %}">
              <a class="page-link" href="?page=1{{ getvars }}">
                  <span aria-hidden="true">&larr;</span>
              </a>
        </li>
        {% for page in paginator.page_range %}
            {% if forloop.first %}
                <li class="page-item {% if page_obj.number == 1 %}disabled{% endif %}"><a class="page-link"
                    href="{% if page_obj.number > 1 %}?page={{ page_obj.number|add:'-1' }}{{ getvars }}{% endif %}">
                    <span aria-hidden="true">&laquo;</span>
                </a></li>
            {% endif %}
            <li class="page-item {% if page_obj.number == page %} active {% endif %}"><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
            {% if forloop.last %}
                <li class="page-item {% if page_obj.number == paginator.num_pages %}disabled{% endif %}">
                    <a class="page-link" href="{% if page_obj.number < paginator.num_pages %}?page={{ page_obj.number|add:'1' }}{{ getvars }}{% endif %}">
                        <span aria-hidden="true">&raquo;</span>
                </a></li>
            {% endif %}
        {% endfor %}
        <li class="page-item {% if page_obj.number == paginator.num_pages %}disabled{% endif %}">
            <a class="page-link" href="?page={{paginator.num_pages}}{{ getvars }}">
                <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
      </ul>
    </nav>
{% endif %}